language: ruby
rvm:
  - 2.2.3

sudo: required

services:
  - postgresql
  - docker

branches:
  only:
    - master

# Install the AWS CLI, so we can push asset artifacts up to S3 when merging to master.
# before_install:
#   - pip install --user awscli
#   - export PATH=$PATH:$HOME/.local/bin

script:
  # Run RSpec tests
  - cd rails
  - bundle install --retry=3
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/homeroom_test
  - bundle exec rspec spec
  - cd ..

  # Teaspoon runs Jasmine tests, so it needs a build of the JS code.
  - docker-compose run webpack npm run build:dev
  - cp -r volumes/webpack_build/dev rails/public/webpack_build/dev
  - cd rails
  - bundle exec teaspoon
  - cd ..

  # Build for production
  - aws/rails/build_from_travis.sh

deploy:
  provider: s3
  access_key_id: $S3_UPLOAD_ACCESS_KEY
  secret_access_key: $S3_UPLOAD_ACCESS_SECRET
  bucket: somerville-teaching-tool-cdn
  skip_cleanup: true
  local_dir: volumes/webpack_build/production
  upload_dir: production/js

env:
  global:
  - secure: ItIXJnhdTGduR/w2xNNFLauu9CWWzwX/QdTaXXjBTBI7inCNuRUWdCuBQbwH0LJFGeAvwRUURdrtMF+ICIAQR0Lp6eYkXwhzldpt5jKMGkXg0ZnDrY4wvYY98Jlt/sXatxIilsjlEDQ8LXMHprKw+4hhD1Bnz073ua2pN4H7550=
  - secure: p0LVATEgItbQa1rN4coZ79UYwH5Bi5fvtKT9MUyTHpnc2HwdgpWuTlaO1/JOsSqB1dxEfuZuC5BuMJiILm3GDMRXkBQbnbl7wYZxeULtYdufOFR0GBc3/gvzkCzbHEOlV3WklyRiHRmTzNVu5drAi5l4rxgeVco6mxGqAPgbdmo=
  - secure: VNxzlxxz658oWvcmefKbJ2Ec+CjSl0+25GNmgIcdbOQscGYJGGK/AF8CLW8rjjgAZSM4UdZrdcXNG315c3LCYQTE6xSIBcTbUuls21WmmvwAnz1cNgmgOYevozDNUeYWA2IYNCpojvxuk1Y0cSqkKThIfczI6wQzzF8bad0tG5g=
  - secure: CVsj/OoauR/2rTan1fAriyW/b92DahJsQ3zh7MAHAeQZ3atRQq4cYxd6fRSO4zoAOeTTTHp4hQ3YX+Uo765bNXsUJLKiKT8Wnin+eOG8nMGxzmKM6oxuWIt552pbwvhuX3+GS8QDT1sbHAdedlDng/97BhXeZTuzgVXN6Zigdo8=
  - secure: jSWLU8N9ui5BZ7PmWmY08BrrOx1BN1IEdYhrTnv5RDWMbUyGTu62hyXOseKMy1b+URaWSiklkxLBK0uVm1oSYf/MYiDhNwFTqPn8eH7AK7MJcxSOaJ4ce0eCEeTy56Wnbljjt0jYeGMFS05uBGhUT82vYvXq4l4h7pCORJWXaPA=
  - secure: Rl1K2PFb0CwnwbFGeA2bRxPSEO4NZEaJ9Z4iADU2/hQ9qUL7GzNuYsuvvubT58K52awa5kOLSFKp0HKyygifrV4PgUG8ebr4tlK1x/kxltaoI92220yZTR2scQWULpjOdddNPK/E2JNbePRhkhstUA8ZDMhbqYGJ17WOR0syFow=
  - secure: UrWfCKjit5P3QVJDIJPf1lzsY0e6qWEABVhfzaQvH6xwjaTlmhk44MGv/Yy9YywSY1qjTeERwvmDe7d5Zy32heJxKb8+ERcIPX0BPCO3l5mHnV1a1DgXsNaiMCekCgA5Ip1FFqgCIpG6MRuFPj/gn9j+pR6Exjeoi2Lg67kTFfs=
  - secure: SBFZJOrZ1D9tgGoLsgWFkEUmO91kaGd4SMCgCIUAtmRK4X9JI+1Kh/0jedIAq0CF8Xe65yEwulXCxOQQNVSa6ARVjBg+8h3ylRVhPsJFkutQcwXDktFvDL3lG/yWekELUFoU01k35Y7ivxsNWWMKo4fbIPPWLrmGk+llvn1kxfdZ15By3Kz/RyUwR1E6+NMRFaSh2GtJaVJVYl1nl9/9VuUDf1KprhlCGAqqbd58FgTxrPhMVBA5mZXBTFzL3yOayXp/L15f0HLMo2u0o/B/e5KB/nGwybvI8iFjIHhLxLl9lnGIEJj12LELRHxFByvcVeq5VoTEe9Qu+uWSvcReuZCtQEAfgdn44RSjoEL8OqyLkrPus1lcx0ZTgRkQ8QKGBagSrt3b144/n+7eFMfTyw2P153c4X1paWqU5uBY/UHz5oVQVL3iyqQMXiEcqMIz7qi4Y28VixptgujM5TJmmixGiIJPf+ptsK05Z7m+WKjCqp6IB8+eMjM8GpXC33kowfGl9etc4fPmddKoTY8YRjq5u8n0hUizyoaI7DgPNOif5C7v1Y8viosYpqNMQNrGm2QK+RfEoH+bo8RPQEWH0d7fRZLFaHG+WeWhTAiOblsw3Gr9fFC7kLkR0Q1TmE6hDysiYJgorIAamR6ZVwBEx1uMVjBBaXiMW2j04MoRDKk=
  - secure: IaXrjGHQqP4cT4WvLrFh3x7KJRK4xI7WPFFgrtRzExkbj0682Yfei8REdqOvnVDTRI7h0Dp2FfyYwWGaOWIW1wYQbALBYXZQ8mPHurw6wWSqgmX/JmwE2AjGL8KqhmkPUDEFug8YjidSivQe3ejlekEgF+kKSmY4iLV2CDjIk3BPlRboncIsPHgOwLKzpPHt/RLegLdgWza11fI7+9EjoaTXwZqQnIrHCEXwOawu26mTVENZKK8OW8rfKuR6rDw+2/yEeLoyMd0xbuXqnqJ6c7CGd1B8SaYjwnqZV9cW9W+WOsPlVEU9EaM5ULCnDWb5Jh/Reiw+TL9DcQtNvKGYXEt4fg6rITm0WJkS48F3SiI5DHT+FIt00jOjuHHxLuAUgw7mw/Yg+lkmZrnc5az+A9L0YPFx/yL5r6ZSqBlOPNkMeYXQY+a+kIM7YwaBN5EjNTwA8/F/+Njhu15NnOw7avtlnrqIl8+nm+WUTUJZ6vczkCMcrsMWbpcClPgeNLRs3lr8fRUfzeBhyUYeyaHD39GJiHGbozdaB4Gdb8PshL0vXdkn11BCnXmKhefHvegEf4CXkhkXAaoahesTqyFeEcXefEPXI60YTW5ykvgjmnVVsTMKn0lOuw/z4RVTkiMPjUBkxRJAnJ1Y8rTuGU+D19f2c6EET8s/B/5cPJXVPYc=

notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/somerville-teacher-tool/status
  slack:
    secure: Px/yHNMrtJQBT9eQ6cUaT/T0YpZf6Mu/RxKWyB7NUwBDj7I1/tH5aZUgB+q2dVL6J29Q5WmxWQXgJz1nMsaH7rPyEXmO2BGI/sdDd5cbSZXSfhS0Uxax9fquPAhBh3tuGexOMBGOktSc5g7fGK2pWQ3CMoT/GkBTwnAV7dSmQxxwLE7VxvLWdTzGWoCSsvkExwcnsosx3psl2gthV0jV4CFzpY9LSPaaQA9lpCHp9yp3JcJQ/XRKUdAcjI5I+A0Mbt75g5l/MEIITjaHs2MUwgz3pAM4b2ma+9SkUNxoH35DWes15I42pY3NG/MCweHIiXWxhUuBEdellY40DOFciH8CQ1keszOG5lJwDzc3Vj+sAHn/cBCRLgUJR2Z4jLdX5/l6knjZ/dHIl3jjB+fDMjclPIoUeJW5EAlWhjt1uMcpCMyJPUnpwKhC8on4qP+DYWVhoAGbrN+57f8bhhRRREy+qCyP+RwESd6fQOfkCa4my5qs0U/tRFvqGlo0H4jpXgfhM/+5DCob9W0c3RfB4wzzSyybeoJyJPvYRx/KJQFX64iL4/sF5Scu6gMGP4bju9qUlZA5KDKySEO7KlJNEUAMSV+T4r8sEVo4uj4+I8z29Bt3DH029Yet0BJAf4gAHVqsm4ewGPvwerf88FDJHjavWSItDagt/RiCZhRXEjk=