language: ruby
rvm:
  - 2.2.3

sudo: required

services:
  - postgresql
  - docker

# Install the AWS CLI, so we can push asset artifacts up to S3 when merging to master.
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

script:
  # Run RSpec tests
  - cd rails
  - bundle install --retry=3
  - bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/homeroom_test
  - bundle exec rspec spec
  - cd ..

  # Teaspoon runs Jasmine tests, so it needs a build of the JS code.
  - docker-compose run webpack npm run build:dev
  - cp -r volumes/webpack_build/dev rails/public/webpack_build/dev
  - cd rails
  - bundle exec teaspoon
  - cd ..

  # Build for production
  - aws/rails/production_build_from_travis.sh

env:
  global:
  # s3 upload, docker hub
  - secure: fUgirCkwbIJ975d1U4z79g7sd9rFFLDgcy99GBDthaKibEofjEC9BXmdYA3oF8JN+4cWz/rVnvuNYBaoeekXg04fIDpRqSZVZeq3Lh83OK4G15l9NySZS721TVjO4YRzuMP5h9ptLs4kZDnJwYFR5CAUxVEluVRDpAXhLDiU6ikenvqnIADrDLwwQktKepIdxGno0ZeOXpb4EV21ueTsoehgjcS7G0FRZcTadeiA1OBo1qqz4SXa+0wrq4eo186gh7LaZnGO08jNQT+YKB9miKYUNOkg0I1mfAkiniztiZ6jfCOOo8fxUgHEC+1/UxfTZs+Ea4Sz7cuz/7qL4w9+zauyUUxvwJZycpuiQdzAXU42abPl3ngx8bX0jDm3zaoa+9Lh50dQlmedbgtsPY7/5bUc7s5FCHHpXfel+e7QbkDn23y38qBHmNx87M+BbWQcc6aHiilFzjS+3YW7lqatj8x48GhkemF2Cxmy3UOeUfOHsnx4AUdPuZNsiVIuDXyMlRh+T8fKN7bhZ7gay21JEHmh3DYeVUlp8+JOrvKISa2VRGTZ4Jn9L7kLioLKlkLJUiBpfrbkD5M2YEBEFMm/O1oFMPR/iSYw/Ylx5dHIn3Hmkp4d7tLlLq8CZed7HqdOxHdrv3kgT58k/72qghbLIQC/Cy6S0df4ApjXL0qvJvc=
  - secure: Q4B+as4AwW6Col6OfXNEblVy6mtcJJdXoplc2J1Lgx7k98r9Yh4onTy/zKRBBIf08qu8kx9EAJG7Qq+A+4TzrfauK1jVYLLYTvtvQntwlOJBKH6S1bbopqpgOfT7/wN5LeCHHDPBUktHDeolBaxumVYfiqlCJkvQF4HKi0wy9ayKVbVe6TVfdz448ZBSM8Mk6Tf0nH605IwYvuOxiD1W9EZS5UYSdbmVZQo8V/OFMULe3XtHZE8EX5zHNus11ybAnArBamm1Woc3gd+8SF3R0Fn6LVpusaUt4z/VEVlXLJPPJgSo9sc+g5SKNlYN7tcpJKyGCx/FqPtv9hWwlAK/39e99nfj1FsbLmuDBoFA8G1xKAeh/drHdqu/FvEA0La0weCZNwE0JK+4Y7oVDuflDLpaAZUT1VCQyzSqF9Xop/FUxguap7QDpkNTkn+tM97zGdxuRYA4aYlC4IWlVTuwmSuhaQ/Ok/F2p8BkoZTnd8AZkSVwQ1XGGtAtcVfRQVugHeZ2913+f7PDxHN/m7JcmKMf4aAVKbcxU6K9ueBZQWl6Lq2LnGwjC5xxYFlj7lxkKkJZnXWG//2SneIFu+/SSXZao5O7ECTcSIxtJP30hX+jvgGNIQjVXi8VZ9GqoiOLNm2s6mYyGADEEX5SeyZSMNWF8y7tK7TLZnZGXOCzZEg=
  - secure: EMMQHJb1pW40PW0UBb6/nGrl5rjLx4Bgz5cCmQigCBvyZEANSHgHIk54yXv9Ia8f7b0bMmmPvgBssSFF8cn0cDzJiVlVxSfp3sIRrZ3sJlvUCEOxPEAwQW/4BIFIvf5zgioNDOzlFWILpZpWi/8HGjTViC2+/qReqcUf4lvXVLUjHS5ZY3/ElU9RD79vWxNutmqJVdv4aQU2RF23CQo5gdE1UIzKOpAT8HrQrtNADJAhZIgAPlgwvEvrxHZgwaRh1EVw1tF12nrMiokzEBN4OHH0NAod5uvQok8oqEHbZcjkM+ARcFOBtTOSI7qhIYdKhapE8+iQKBLU4CiOBN791pGkP+CEtDxTHGX5VXee0u1k22f7lo8vK468sqC5QvrC3HOB5HJ/g6Do3YO+M3w966617uu89SgHiiHX9m7XsEFd/EtEHyDo7liIjGFXb2G4qhmypMsXBWGeVefo+7BEAy/lQ0Pdvy+CydQXkReqeR3FoaguCO4m/ilu6IK5F9RBn4K+G9JyuWUU03LV56wWmjpgsToByoVxn/SzsLd2miNYSE65FyJIOBO8JmT4y8L08wCy4yPSHWWN2TAWkl4RxL/lCgEQnAsSbYYFraAf3tWKASoOxkQVdtoPE7QJ/QS8wgxxaNSn99G8IZQMSwDpU7hNxS+fZCgphTkDCtctbMk=
  - secure: UEc4DThmh3IK5RFBTvIKeDjuI2ya11emuWySB6MAO95vjs+5hqaD10BBppBlcP0MasjaulWHVjVGYJhWB1Igt+6R1WZEJzeC5g0rWHhdObLAMGCn4U81xO9fuFPLtC/XQ5G0vsRffCiN25BS367X4aPYEt/EYTS9Cpc4AmrxLSIlXanxu49wqHGhwzSrwLHUD0kGifBZk8+1l+Jnqg1CqXyT2nILer1gmrm2WqeGmtd+qbPKVqqhVB0WGnjOkx45EBYalYCIkrw6sn70VMcCkXAZHjhgWu+SNiu1BdxI7ZHQC6djjt+lnMhYGUN6w4+LV4kUA5z8Bqml1BxE614+cxpOYqZFku4n5J9Dksm9Vq67AfC8XY4IoeZ/mDUvGQ82Hex6KfBRxiUyw2mB5imUxLj5wfdyw+af1DMN1qdx/aM4pyRS5wPoT3S0VY7SKHxpDYDwIhkNJN8wl3I+Mhu2q0RO7yujyA0oKbje8+itsu6Q1vx/t1A42FwKUoPEcUiOxMIB8fDy/Sz2uVMKDskYYdKZqxqxcfuNC5MrVT62pcLdd8GteiIbUqnrqyxgfxWEjx1xnot/0Et3ezz5RJAwChNaDLyw3+Q5fDP/SBXSfZtWschdC7d5K3Nj5/HXV/Yn71lHly4zNkD1aZPdVB2am+AdRk5f6aUHQaOG5M09HI0=
  - secure: BXwPEMykKEzXdn2hZ+KWsy36RrVpNKXz6GQEPAEQ1U+5t+pBIpiJoE8/lksMeL8Ljxw9cmNOaOySi5rLIlBxEasFZqqPDuERIsDEUTS/o1N8R3YfilHxOF9g7QRSQmOHvUCtLnCJW+GiDPsUuUwxX9Jf4Z5Y5WDKc8eSVhyhErl1d2gZVLPdhHn06aHHpjERmkXaMXx6h3B2wWUg5DXy5Eo6mojOZ1ojb8K/p8EulBdYUrO2XBXQmBnBdPMhFPZFLl7QiXVvunCcaBc/vucPsz3s59A3ZMDx+uWHiEoVHyd/bFyxU8A4Ll8psbheQqOrah4S7f14nfuYZkzw6o8bYpwbx72128JpVbjEoZmhvLC0kjCN1dBvcYjsELvhPUiH5r3e1K0HcnULMEd4y8k/Yw5R+l/SCakN4QN31euXLl0QAg666tD/L4LMVCtDtH1tA0Ioogq1t2gzHy74mzpiktntx1JGpdg6HwuZCYngecpRKp0nkMjwObqCVI4dxcuKWouOobkDPkV4fzR3kAM9ldrqQ/nIOf61E6i+KoUPpkPLuQuNDgzO+Td0jm1th8L5nl3aDHeUKc1w8RSvvGHbgD/fRP9HJWN3wCfnX3F5mmis14DygouyAbvUHQyb5oGaAe/8v6Yijcc0Ysf5eELjwVmLWQdKSg4w+BfloKWk9Cc=

notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/somerville-teacher-tool/status
  slack:
    secure: Px/yHNMrtJQBT9eQ6cUaT/T0YpZf6Mu/RxKWyB7NUwBDj7I1/tH5aZUgB+q2dVL6J29Q5WmxWQXgJz1nMsaH7rPyEXmO2BGI/sdDd5cbSZXSfhS0Uxax9fquPAhBh3tuGexOMBGOktSc5g7fGK2pWQ3CMoT/GkBTwnAV7dSmQxxwLE7VxvLWdTzGWoCSsvkExwcnsosx3psl2gthV0jV4CFzpY9LSPaaQA9lpCHp9yp3JcJQ/XRKUdAcjI5I+A0Mbt75g5l/MEIITjaHs2MUwgz3pAM4b2ma+9SkUNxoH35DWes15I42pY3NG/MCweHIiXWxhUuBEdellY40DOFciH8CQ1keszOG5lJwDzc3Vj+sAHn/cBCRLgUJR2Z4jLdX5/l6knjZ/dHIl3jjB+fDMjclPIoUeJW5EAlWhjt1uMcpCMyJPUnpwKhC8on4qP+DYWVhoAGbrN+57f8bhhRRREy+qCyP+RwESd6fQOfkCa4my5qs0U/tRFvqGlo0H4jpXgfhM/+5DCob9W0c3RfB4wzzSyybeoJyJPvYRx/KJQFX64iL4/sF5Scu6gMGP4bju9qUlZA5KDKySEO7KlJNEUAMSV+T4r8sEVo4uj4+I8z29Bt3DH029Yet0BJAf4gAHVqsm4ewGPvwerf88FDJHjavWSItDagt/RiCZhRXEjk=