# This is based off https://docs.docker.com/compose/rails/
#
# Asset compilation works by having the webpack container continually build an artifact,
# and that artifact being mounted for Rails to serve statically.
rails:
  build: rails/.
  environment:
    DATABASE_URL: postgresql://postgres@postgres # overrides hostname and username
  ports:
    - "3000:3000"
  links:
    - postgres
  working_dir: /mnt/rails
  command: bundle exec rails s -b '0.0.0.0'
  volumes:
    - ./rails:/mnt/rails
    - ./volumes/webpack_build:/mnt/rails/public/webpack_build


webpack:
  build: webpack/.
  command: npm run watch
  volumes:
    - ./webpack/config:/mnt/webpack/config
    - ./webpack/src:/mnt/webpack/src
    - ./volumes/webpack_build:/mnt/build

postgres:
  image: postgres
  ports:
    - "5432:5432"
  volumes:
    - /var/lib/postgresql/data